import type { Metadata } from "next";
import { headers } from "next/headers";
import Link from "next/link";
import type { ReactNode } from "react";
import { Wordmark } from "@/components/art/wordmark";
import { Dateline } from "@/components/ui/dateline";
import { kitBody, lineupBody } from "@/lib/api-shapes";
import { getLineup } from "@/lib/lineup";
import { loadKit } from "@/lib/queries/kit";
import type { BriefValue } from "@/lib/types";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Developers", description: "A small, public, read-only JSON API: ranked lineups and creator kits." };

const BRIEF: BriefValue = { product: "", buyers: ["CTOs", "Security leads"], verticals: ["Fintech"], geo: ["France", "Germany"], budgetCents: 600000 };

function Code({ children, label }: { children: string; label: string }) {
  return (
    <pre tabIndex={0} aria-label={label} className="overflow-x-auto border border-line-strong bg-paper-2 p-4 font-mono text-caption leading-relaxed">
      <code>{children}</code>
    </pre>
  );
}

function Endpoint({ id, method, path, children }: { id: string; method: string; path: string; children: ReactNode }) {
  return (
    <section id={id} aria-labelledby={`${id}-h`} className="scroll-mt-4 border-t-2 border-ink py-10">
      <h2 id={`${id}-h`} className="font-mono text-title [overflow-wrap:anywhere]">
        <span className="text-muted">{method}</span> {path}
      </h2>
      <div className="mt-4 grid gap-5">{children}</div>
    </section>
  );
}

export default async function Developers() {
  const h = await headers();
  const host = h.get("x-forwarded-host") ?? h.get("host") ?? "localhost:3000";
  const proto = h.get("x-forwarded-proto") ?? (host.startsWith("localhost") ? "http" : "https");
  const base = `${proto}://${host}`;

  let lineup = "{ \"error\": \"unavailable\" }";
  let kit = lineup;
  try {
    const l = await getLineup(BRIEF, 2);
    lineup = JSON.stringify(lineupBody(BRIEF, l.total, l.creators), null, 2);
    const d = await loadKit("maya-okafor");
    if (d) {
      const b = kitBody(d.kit, d.posts.slice(0, 1), d.receipts.slice(0, 1));
      kit = JSON.stringify(b, null, 2);
    }
  } catch {
    // docs still render without live examples
  }

  return (
    <div className="mx-auto max-w-4xl px-4 pb-20 pt-6 sm:px-6">
      <header className="flex items-center justify-between border-b border-ink pb-2">
        <Wordmark />
        <Link href="/" className="inline-flex min-h-11 items-center text-small underline decoration-line-strong underline-offset-4 hover:decoration-ink">
          Back to Byline
        </Link>
      </header>

      <main id="main">
        <div className="pt-10">
          <Dateline>Developers · public API · read-only</Dateline>
          <h1 className="mt-1 text-display-xl">A small, honest API.</h1>
          <p className="mt-4 max-w-prose text-body text-muted">
            The landing page&rsquo;s live desk is this API: it ranks the public catalogue for a brief, straight from the database. No key, no sign-up. Everything below is generated by the same code that serves it, so the examples are what you will get.
          </p>
          <dl className="mt-6 grid gap-3 border-y border-line py-4 text-small sm:grid-cols-3">
            <div>
              <dt className="font-mono text-caption text-muted">Base URL</dt>
              <dd className="break-all font-mono">{base}</dd>
            </div>
            <div>
              <dt className="font-mono text-caption text-muted">Limit</dt>
              <dd>60 requests a minute per IP</dd>
            </div>
            <div>
              <dt className="font-mono text-caption text-muted">Caching</dt>
              <dd>Public, 30 s; CORS open</dd>
            </div>
          </dl>
        </div>

        <Endpoint id="lineup" method="GET" path="/api/lineup">
          <p className="text-small text-muted">The ranked lineup for a brief. Every creator carries a fit score (0–100), the reasons behind it, and a click projection.</p>
          <div className="overflow-x-auto" tabIndex={0} role="region" aria-label="Parameters">
            <table className="w-full min-w-[32rem] border-collapse text-small">
              <caption className="sr-only">Query parameters</caption>
              <thead className="border-b border-ink">
                <tr className="text-left font-mono text-caption text-muted">
                  <th scope="col" className="py-2 pr-4 font-normal">Parameter</th>
                  <th scope="col" className="py-2 pr-4 font-normal">Meaning</th>
                  <th scope="col" className="py-2 font-normal">Example</th>
                </tr>
              </thead>
              <tbody className="[&>tr]:border-b [&>tr]:border-line">
                {[
                  ["buyers", "Buyer roles, comma-separated", "CTOs,Security leads"],
                  ["verticals", "Verticals, comma-separated", "Fintech"],
                  ["geo", "Audience countries, comma-separated", "France,Germany"],
                  ["budget", "Budget in whole euros (adds nothing to the score; flags nothing)", "6000"],
                  ["limit", "How many creators, 1 to 40 (default 12)", "6"],
                ].map(([k, m, e]) => (
                  <tr key={k}>
                    <td className="py-2 pr-4 font-mono">{k}</td>
                    <td className="py-2 pr-4">{m}</td>
                    <td className="py-2 font-mono text-caption">{e}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="text-caption text-muted">Unknown values are ignored, not rejected. Every facet you leave empty is neutral, so an empty brief ranks on performance alone.</p>
          <Code label="Example request">{`curl "${base}/api/lineup?buyers=CTOs,Security%20leads&verticals=Fintech&geo=France,Germany&budget=6000&limit=2"`}</Code>
          <Code label="Live example response">{lineup}</Code>
        </Endpoint>

        <Endpoint id="creator" method="GET" path="/api/creators/{handle}">
          <p className="text-small text-muted">A creator&rsquo;s public kit: profile, recent posts and paid Receipts. Audience and reach numbers are self-reported and labelled so; only the clicks on a Receipt are verified.</p>
          <Code label="Example request">{`curl "${base}/api/creators/maya-okafor"`}</Code>
          <Code label="Live example response (one post and one receipt shown)">{kit}</Code>
        </Endpoint>

        <Endpoint id="health" method="GET" path="/api/health">
          <p className="text-small text-muted">Proves the service is wired to a real database. Counts only.</p>
          <Code label="Example request">{`curl "${base}/api/health"`}</Code>
        </Endpoint>

        <section aria-labelledby="errors-h" className="border-t-2 border-ink py-10">
          <h2 id="errors-h" className="font-serif text-title">
            Errors
          </h2>
          <p className="mt-2 max-w-prose text-small text-muted">Errors are JSON with a stable code and a human message: 400 for a bad parameter, 404 for an unknown creator, 429 when you are over the limit, 503 if the database is unreachable.</p>
          <div className="mt-4">
            <Code label="Error shape">{`{ "error": { "code": "rate_limited", "message": "Too many requests. The limit is 60 per minute." } }`}</Code>
          </div>
          <p className="mt-6 max-w-prose text-small text-muted">All creators and brands in the demo are fictional. The API is read-only and exposes nothing that is not already on a public page.</p>
        </section>
      </main>
    </div>
  );
}
